services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - web_data:/usr/share/nginx/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    restart: always

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "2222:22"
    volumes:
      - web_data:/home/webuser/upload
    command: webuser:webpass:1001:1001:::upload
    restart: always

volumes:
  web_data:
